packages:
  - 'packages/*'

# Centralize shared dependency versions (pnpm 8.15+)
catalog:
  # Shared runtime deps
  zod: ^3.24.0

  # Build tooling
  typescript: ^5.9.3
  '@types/node': ^22.19.3

  # Testing
  vitest: ^2.1.9
